# src/Stsbl/FileDistributionBundle/Resources/config/services.yml
services:
    stsbl.filedistribution.crud.file_distribution:
        class: Stsbl\FileDistributionBundle\Crud\FileDistributionCrud
        arguments: [Stsbl\FileDistributionBundle\Entity\Host]
        calls:
           - [ setShell, ["@iserv.shell"]]
           - [ setEntityManager, ["@doctrine.orm.entity_manager"]]
           - [ setSecurityHandler, ["@iserv.security_handler"]]
           - [ setSession, ["@session"]]
           - [ setConfig, ["@iserv.config"]]
           - [ setRequest, ["@request_stack"]]
           - [ setRpc, ["@stsbl.filedistribution.rpc"]]
        tags:
            - { name: iserv.crud }
            
    stsbl.filedistribution.menu:
        class: Stsbl\FileDistributionBundle\EventListener\MenuListener # Out MenuListener Class
        tags:
          - { name: kernel.event_listener, event: iserv_portal.menu_main, method: onBuildMainMenu } # Tells IServ about the main menu method
    
    stsbl.filedistribution.rpc:
        class: Stsbl\FileDistributionBundle\Service\Rpc
        arguments: ["@iserv.shell", "@iserv.security_handler"]
    
    stsbl.filedistribution.twig.extension.base64:
        class: Stsbl\FileDistributionBundle\Twig\Extension\Base64
        tags :
          - { name: twig.extension }